### ISSUE TITLE
有点问题 -HA中文下，配置报错。切换到英文可以配置，但是无法接入，集成里显示no found

### ISSUE THREAD

**Issue by flyice-juin** [huishizhao/Baidu_sst#1]
HA中文下，配置报错。切换到英文可以配置，但是无法接入，集成里显示no found

**Comment by huishizhao** [comment]
> HA中文下，配置报错。切换到英文可以配置，但是无法接入，集成里显示no found

英文已经更新一版，请重新下载，中文版配置信息已更正。
请重新下载使用
